SERPER_API_KEY: 4d3b0b5e6aa6460958c51043b4f8cbe336761c37
OPENAI_API_KEY: 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
