OPENAI_API_KEY = "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"
SERPER_API_KEY = "4d3b0b5e6aa6460958c51043b4f8cbe336761c37"
